# Phase 1

In [2]:
import numpy as np 
import pandas as pd

0. It seems that the purpose of the exercise is to try to do the instruction myself before actually running the help code. This is great as I don't know the functions necessary check whether there are NA values and how many

In [3]:
week_one = pd.read_csv("traslados_semana_1.csv")
week_two = pd.read_csv("traslados_semana_2.csv")

1. While VSCode allows me to see the arguments that a specific function of a library expects, to be honest those are practically useless for me that I lack complete understanding on the functions of the library. As now I have `tlrc` in my global `configuration.nix` am I able to have clear explanations of each function in the terminal about a specific library? or are these limited to simply shell commands?

In [4]:
print(week_one)
print(week_two)

   id_registro       fecha id_ruta  duracion_min costo_mxn      medio
0          101  2026-02-02    R-01          32.0     12.00        bus
1          102  2026-02-02    R-02          41.0      0.00  bicicleta
2          103  2026-02-03    R-01          46.0         -         ND
3          104  2026-02-03    R-99           NaN     12.00        bus
4          105  2026-02-04    R-02          28.0      8.50        bus
5          106  2026-02-04    R-01          35.0     12.00        bus
6          107  2026-02-05    R-02           NaN         -  bicicleta
7          108  2026-02-05    R-03          15.0      0.00  bicicleta
8          109  2026-02-06    R-01          30.0     12.00        bus
9          110  2026-02-06    R-02          44.0      8.50        bus
   id_registro       fecha id_ruta  duracion_min costo_mxn      medio
0          201  2026-02-09    R-02          40.0      8.50        bus
1          202  2026-02-09    R-01          33.0     12.00        bus
2          203  2026-02-10    R-01          35.0     12.00        bus
3          204  2026-02-10    R-02          42.0      8.50        bus
4          205  2026-02-11    R-03          18.0      0.00  bicicleta
5          206  2026-02-11    R-99          22.0         -         ND
6          207  2026-02-12    R-02           NaN      8.50        bus
7          208  2026-02-12    R-01          31.0     12.00        bus
8          209  2026-02-13    R-01          36.0         -        bus
9          210  2026-02-13    R-03          14.0      0.00  bicicleta

2. How cool! I thought I was going to get some random memory adress of where the object was located but I actually got a tabular version of the data. As they're short I can completely see them both without problem

In [5]:
week_one.isna()

   id_registro  fecha  id_ruta  duracion_min  costo_mxn  medio
0        False  False    False         False      False  False
1        False  False    False         False      False  False
2        False  False    False         False      False  False
3        False  False    False          True      False  False
4        False  False    False         False      False  False
5        False  False    False         False      False  False
6        False  False    False          True      False  False
7        False  False    False         False      False  False
8        False  False    False         False      False  False
9        False  False    False         False      False  False

3. With this I can visually see that the only column in which I have NAs is on `duraction_min`. Is there a function that gives me how many and in which columns? It seems I can combine it with `sum()` to know precisely how many there're

In [6]:
week_one.isna().sum()

id_registro     0
fecha           0
id_ruta         0
duracion_min    2
costo_mxn       0
medio           0
dtype: int64

4. How pretty! Now I can see how many NAs there are in each of the attributes.

In [7]:
week_two.isna().sum()

id_registro     0
fecha           0
id_ruta         0
duracion_min    1
costo_mxn       0
medio           0
dtype: int64

5. In `week_two` I just have 1 NA in `duracion_min`. 

6. Now... about date interpretation... how am I supposed to do that? it seems that it goes directly as an argument when the variables are created.

In [8]:
other_week_one = pd.read_csv("traslados_semana_1.csv", 
                             na_values=["-"], 
                             parse_dates="fecha")

TypeError: Only booleans and lists are accepted for the 'parse_dates' parameter

5. As it is telling me that `TypeError: Only booleans and lists are accepted for the 'parse_dates' parameter` I see that I cannot simply provide the name of the column. I will try with a numerical value next.

In [ ]:
other_week_one = pd.read_csv("traslados_semana_1.csv", 
                             na_values=["-"], 
                             parse_dates=1)

TypeError: Only booleans and lists are accepted for the 'parse_dates' parameter

6. It doesn't work either... if I already had it in a variable I would do something like `df['fecha']` as the list returned, but I am just initializing it... how would a boolean work? Would it go row by row creating comparissons to see if anything looks like a date?

In [10]:
other_week_one = pd.read_csv("traslados_semana_1.csv", 
                             na_values=["-", "ND"], 
                             parse_dates=True)
other_week_one

   id_registro       fecha id_ruta  duracion_min  costo_mxn      medio
0          101  2026-02-02    R-01          32.0       12.0        bus
1          102  2026-02-02    R-02          41.0        0.0  bicicleta
2          103  2026-02-03    R-01          46.0        NaN        NaN
3          104  2026-02-03    R-99           NaN       12.0        bus
4          105  2026-02-04    R-02          28.0        8.5        bus
5          106  2026-02-04    R-01          35.0       12.0        bus
6          107  2026-02-05    R-02           NaN        NaN  bicicleta
7          108  2026-02-05    R-03          15.0        0.0  bicicleta
8          109  2026-02-06    R-01          30.0       12.0        bus
9          110  2026-02-06    R-02          44.0        8.5        bus

7. My intuition of passing a list with the literal strings in which the data is passed that it describes as a missing value works... but I still don't know if I managed to parse the dates. When I hover my mouse over `fecha` I just get that it is a string... my problem was that I was not passing a list! I imagine there might be data frames in which there are more than one date (such as an e-commerce with "date purchased" and "date delivered" or something like that). Then what was accomplished with `parsed_dates=True`?

In [11]:
other_week_one = pd.read_csv("traslados_semana_1.csv", 
                             na_values=["-", "ND"], 
                             parse_dates=["fecha"])
other_week_one

   id_registro      fecha id_ruta  duracion_min  costo_mxn      medio
0          101 2026-02-02    R-01          32.0       12.0        bus
1          102 2026-02-02    R-02          41.0        0.0  bicicleta
2          103 2026-02-03    R-01          46.0        NaN        NaN
3          104 2026-02-03    R-99           NaN       12.0        bus
4          105 2026-02-04    R-02          28.0        8.5        bus
5          106 2026-02-04    R-01          35.0       12.0        bus
6          107 2026-02-05    R-02           NaN        NaN  bicicleta
7          108 2026-02-05    R-03          15.0        0.0  bicicleta
8          109 2026-02-06    R-01          30.0       12.0        bus
9          110 2026-02-06    R-02          44.0        8.5        bus

8. Now it indeed looks different as there are now `00:00:00` after each of the dates, which I assume are "hh:mm:ss".

# Phase 2

9. The best way to automatize this is to create a function.

In [13]:
def check_data(df):
    print(f"The shape of the data frame is: {df.shape}\n")
    print(f"The data type that pandas infered is {df.dtype}\n")
    print(f"The total missing values of the dataframe is: {df.isna().sum()}\n")

check_data(other_week_one)

The shape of the data frame is: (10, 6)

AttributeError: 'DataFrame' object has no attribute 'dtype'

10. I got the error `AttributeError: 'DataFrame' object has no attribute 'dtype'`... and also I don't know how to check if there're duplicates. I might do the latter with `np.where`

In [14]:
other_week_one.where((index == index + 1), duplicates, originals)

NameError: name 'index' is not defined

11. Here the problem seems fairly obvious: I don't have an index nor a concrete way to check each of the indexes and compare to one another... it makes sense, numpy was designed to work with simple functions instead of depending on `for` loops.