# Phase 1

In [1]:
import numpy as np
import pandas as pd

0. It seems that the purpose of the exercise is to try to do the instruction myself before actually running the help code. This is great as I don't know the functions necessary check whether there are NA values and how many

In [3]:
week_one = pd.read_csv("traslados_semana_1.csv")
week_two = pd.read_csv("traslados_semana_2.csv")

1. While VSCode allows me to see the arguments that a specific function of a library expects, to be honest those are practically useless for me that I lack complete understanding on the functions of the library. As now I have `tlrc` in my global `configuration.nix` am I able to have clear explanations of each function in the terminal about a specific library? or are these limited to simply shell commands?

In [4]:
print(week_one)
print(week_two)

   id_registro       fecha id_ruta  duracion_min costo_mxn      medio
0          101  2026-02-02    R-01          32.0     12.00        bus
1          102  2026-02-02    R-02          41.0      0.00  bicicleta
2          103  2026-02-03    R-01          46.0         -         ND
3          104  2026-02-03    R-99           NaN     12.00        bus
4          105  2026-02-04    R-02          28.0      8.50        bus
5          106  2026-02-04    R-01          35.0     12.00        bus
6          107  2026-02-05    R-02           NaN         -  bicicleta
7          108  2026-02-05    R-03          15.0      0.00  bicicleta
8          109  2026-02-06    R-01          30.0     12.00        bus
9          110  2026-02-06    R-02          44.0      8.50        bus
   id_registro       fecha id_ruta  duracion_min costo_mxn      medio
0          201  2026-02-09    R-02          40.0      8.50        bus
1          202  2026-02-09    R-01          33.0     12.00        bus
2          203  2026-02-10    R-01          35.0     12.00        bus
3          204  2026-02-10    R-02          42.0      8.50        bus
4          205  2026-02-11    R-03          18.0      0.00  bicicleta
5          206  2026-02-11    R-99          22.0         -         ND
6          207  2026-02-12    R-02           NaN      8.50        bus
7          208  2026-02-12    R-01          31.0     12.00        bus
8          209  2026-02-13    R-01          36.0         -        bus
9          210  2026-02-13    R-03          14.0      0.00  bicicleta

2. How cool! I thought I was going to get some random memory adress of where the object was located but I actually got a tabular version of the data. As they're short I can completely see them both without problem

In [5]:
week_one.isna()

   id_registro  fecha  id_ruta  duracion_min  costo_mxn  medio
0        False  False    False         False      False  False
1        False  False    False         False      False  False
2        False  False    False         False      False  False
3        False  False    False          True      False  False
4        False  False    False         False      False  False
5        False  False    False         False      False  False
6        False  False    False          True      False  False
7        False  False    False         False      False  False
8        False  False    False         False      False  False
9        False  False    False         False      False  False

3. With this I can visually see that the only column in which I have NAs is on `duraction_min`. Is there a function that gives me how many and in which columns? It seems I can combine it with `sum()` to know precisely how many there're

In [6]:
week_one.isna().sum()

id_registro     0
fecha           0
id_ruta         0
duracion_min    2
costo_mxn       0
medio           0
dtype: int64

4. How pretty! Now I can see how many NAs there are in each of the attributes.

In [7]:
week_two.isna().sum()

id_registro     0
fecha           0
id_ruta         0
duracion_min    1
costo_mxn       0
medio           0
dtype: int64

5. In `week_two` I just have 1 NA in `duracion_min`.

6. Now... about date interpretation... how am I supposed to do that? it seems that it goes directly as an argument when the variables are created.

In [8]:
other_week_one = pd.read_csv("traslados_semana_1.csv",
                             na_values=["-"],
                             parse_dates="fecha")

TypeError: Only booleans, lists, and dictionaries are accepted for the 'parse_dates' parameter

5. As it is telling me that `TypeError: Only booleans and lists are accepted for the 'parse_dates' parameter` I see that I cannot simply provide the name of the column. I will try with a numerical value next.

In [9]:
other_week_one = pd.read_csv("traslados_semana_1.csv",
                             na_values=["-"],
                             parse_dates=1)

TypeError: Only booleans, lists, and dictionaries are accepted for the 'parse_dates' parameter

6. It doesn't work either... if I already had it in a variable I would do something like `df['fecha']` as the list returned, but I am just initializing it... how would a boolean work? Would it go row by row creating comparissons to see if anything looks like a date?

In [10]:
other_week_one = pd.read_csv("traslados_semana_1.csv",
                             na_values=["-", "ND"],
                             parse_dates=True)
other_week_one

   id_registro       fecha id_ruta  duracion_min  costo_mxn      medio
0          101  2026-02-02    R-01          32.0       12.0        bus
1          102  2026-02-02    R-02          41.0        0.0  bicicleta
2          103  2026-02-03    R-01          46.0        NaN        NaN
3          104  2026-02-03    R-99           NaN       12.0        bus
4          105  2026-02-04    R-02          28.0        8.5        bus
5          106  2026-02-04    R-01          35.0       12.0        bus
6          107  2026-02-05    R-02           NaN        NaN  bicicleta
7          108  2026-02-05    R-03          15.0        0.0  bicicleta
8          109  2026-02-06    R-01          30.0       12.0        bus
9          110  2026-02-06    R-02          44.0        8.5        bus

7. My intuition of passing a list with the literal strings in which the data is passed that it describes as a missing value works... but I still don't know if I managed to parse the dates. When I hover my mouse over `fecha` I just get that it is a string... my problem was that I was not passing a list! I imagine there might be data frames in which there are more than one date (such as an e-commerce with "date purchased" and "date delivered" or something like that). Then what was accomplished with `parsed_dates=True`?

In [11]:
other_week_one = pd.read_csv("traslados_semana_1.csv",
                             na_values=["-", "ND"],
                             parse_dates=["fecha"])
other_week_one

   id_registro      fecha id_ruta  duracion_min  costo_mxn      medio
0          101 2026-02-02    R-01          32.0       12.0        bus
1          102 2026-02-02    R-02          41.0        0.0  bicicleta
2          103 2026-02-03    R-01          46.0        NaN        NaN
3          104 2026-02-03    R-99           NaN       12.0        bus
4          105 2026-02-04    R-02          28.0        8.5        bus
5          106 2026-02-04    R-01          35.0       12.0        bus
6          107 2026-02-05    R-02           NaN        NaN  bicicleta
7          108 2026-02-05    R-03          15.0        0.0  bicicleta
8          109 2026-02-06    R-01          30.0       12.0        bus
9          110 2026-02-06    R-02          44.0        8.5        bus

8. Now it indeed looks different as there are now `00:00:00` after each of the dates, which I assume are "hh:mm:ss".

# Phase 2

9. The best way to automatize this is to create a function.

In [12]:
def check_data(df):
    print(f"The shape of the data frame is: {df.shape}\n")
    print(f"The data type that pandas infered is {df.dtype}\n")
    print(f"The total missing values of the dataframe is: {df.isna().sum()}\n")

check_data(other_week_one)

The shape of the data frame is: (10, 6)

AttributeError: 'DataFrame' object has no attribute 'dtype'

10. I got the error `AttributeError: 'DataFrame' object has no attribute 'dtype'`... and also I don't know how to check if there're duplicates. I might do the latter with `np.where`

In [13]:
other_week_one.where((index == index + 1), duplicates, originals)

NameError: name 'index' is not defined

11. Here the problem seems fairly obvious: I don't have an index nor a concrete way to check each of the indexes and compare to one another... it makes sense, numpy was designed to work with simple functions instead of depending on `for` loops.

In [14]:
def check_data(df):
    print(f"The shape of the data frame is: {df.shape}\n")
    print(f"The data type that pandas infered is {df.dtypes}\n")
    print(f"The total missing values of the dataframe is: {df.isna().sum()}\n")

check_data(other_week_one)

The shape of the data frame is: (10, 6)

The data type that pandas infered is id_registro              int64
fecha           datetime64[ns]
id_ruta                 object
duracion_min           float64
costo_mxn              float64
medio                   object
dtype: object

The total missing values of the dataframe is: id_registro     0
fecha           0
id_ruta         0
duracion_min    2
costo_mxn       2
medio           1
dtype: int64

12. Now with the other week

In [15]:
other_week_two = pd.read_csv("traslados_semana_2.csv",
                             na_values=["-", "ND"],
                             parse_dates=["fecha"])
check_data(other_week_two)

The shape of the data frame is: (10, 6)

The data type that pandas infered is id_registro              int64
fecha           datetime64[ns]
id_ruta                 object
duracion_min           float64
costo_mxn              float64
medio                   object
dtype: object

The total missing values of the dataframe is: id_registro     0
fecha           0
id_ruta         0
duracion_min    1
costo_mxn       2
medio           1
dtype: int64

13. Now it is time to check on the zonas and routes

In [16]:
df_routes = pd.read_csv("rutas.csv")
df_zones = pd.read_csv("zonas.csv")
print(f"Routes shape: {df_routes.shape}")
print(f"Zones shape: {df_zones.shape}")

Routes shape: (5, 3)
Zones shape: (3, 2)

14. Now lets check if there are any duplicate ids

In [20]:
print(f"Duplicate ids? {df_routes["id_ruta"].duplicated().any()}")
print(f"Duplicate ids? {df_zones["id_zona"].duplicated().any()}  ")

Duplicate ids? True
Duplicate ids? False

15. I didn't expect to have the duplicate ids.

¿Qué anomalía crítica detectaste en el catálogo de rutas (`df_rutas_raw`) al ejecutar la validación de duplicidad? ¿Qué consecuencias graves traería si unimos esta tabla a ciegas con el DataFrame de traslados mediante `pd.merge()`?

I believe the biggest problem that it could bring is that `.merge()` probably joins by id, so having a duplicate could duplicate the information of a certain journey or simply throw an error.

# Phase 3

16. First of all I need to remove the duplicates

In [21]:
df_routes_clean = df_routes.drop_duplicates(subset=["id_ruta"], keep="first").copy()
df_routes

  id_ruta                               nombre_ruta id_zona
0    R-01                          Ruta Centro-ENES    Z-01
1    R-02                    Ruta Campus Juriquilla    Z-02
2    R-03                           Ciclovía Jurica    Z-02
3    R-04                             Ruta Satélite    Z-03
4    R-02  Ruta Campus Juriquilla (Duplicado Error)    Z-02

17. Now I will create a copy of each of the data frames.

In [24]:
df_week_one_clean = other_week_one.copy()
df_week_two_clean = other_week_two.copy()
print(df_week_one_clean)
print(df_week_two_clean)

   id_registro      fecha id_ruta  duracion_min  costo_mxn      medio
0          101 2026-02-02    R-01          32.0       12.0        bus
1          102 2026-02-02    R-02          41.0        0.0  bicicleta
2          103 2026-02-03    R-01          46.0        NaN        NaN
3          104 2026-02-03    R-99           NaN       12.0        bus
4          105 2026-02-04    R-02          28.0        8.5        bus
5          106 2026-02-04    R-01          35.0       12.0        bus
6          107 2026-02-05    R-02           NaN        NaN  bicicleta
7          108 2026-02-05    R-03          15.0        0.0  bicicleta
8          109 2026-02-06    R-01          30.0       12.0        bus
9          110 2026-02-06    R-02          44.0        8.5        bus
   id_registro      fecha id_ruta  duracion_min  costo_mxn      medio
0          201 2026-02-09    R-02          40.0        8.5        bus
1          202 2026-02-09    R-01          33.0       12.0        bus
2          203 2026-02-10    R-01          35.0       12.0        bus
3          204 2026-02-10    R-02          42.0        8.5        bus
4          205 2026-02-11    R-03          18.0        0.0  bicicleta
5          206 2026-02-11    R-99          22.0        NaN        NaN
6          207 2026-02-12    R-02           NaN        8.5        bus
7          208 2026-02-12    R-01          31.0       12.0        bus
8          209 2026-02-13    R-01          36.0        NaN        bus
9          210 2026-02-13    R-03          14.0        0.0  bicicleta

18. It is time to change the data type for the cost

In [25]:
df_week_one_clean["costo_mxn"] = df_week_one_clean["costo_mxn"].astype(float)
df_week_two_clean["costo_mxn"] = df_week_two_clean["costo_mxn"].astype(float)
print(df_week_one_clean.dtypes)
print(df_week_two_clean.dtypes)

id_registro              int64
fecha           datetime64[ns]
id_ruta                 object
duracion_min           float64
costo_mxn              float64
medio                   object
dtype: object
id_registro              int64
fecha           datetime64[ns]
id_ruta                 object
duracion_min           float64
costo_mxn              float64
medio                   object
dtype: object

19. It worked correctly!. I will just check for the duplicates as a sanity check

In [28]:
print(f"Duplicate ids? {df_routes_clean["id_ruta"].duplicated().any()}")

Duplicate ids? False

# Phase 4

20. I will start with doing a concatenation of both data frames

In [30]:
df_all_trips = pd.concat(
    [df_week_one_clean, df_week_two_clean],
    axis=0,
    keys=["week_one", "week_two"],
)
df_all_trips

            id_registro      fecha id_ruta  duracion_min  costo_mxn      medio
week_one 0          101 2026-02-02    R-01          32.0       12.0        bus
         1          102 2026-02-02    R-02          41.0        0.0  bicicleta
         2          103 2026-02-03    R-01          46.0        NaN        NaN
         3          104 2026-02-03    R-99           NaN       12.0        bus
         4          105 2026-02-04    R-02          28.0        8.5        bus
         5          106 2026-02-04    R-01          35.0       12.0        bus
         6          107 2026-02-05    R-02           NaN        NaN  bicicleta
         7          108 2026-02-05    R-03          15.0        0.0  bicicleta
         8          109 2026-02-06    R-01          30.0       12.0        bus
         9          110 2026-02-06    R-02          44.0        8.5        bus
week_two 0          201 2026-02-09    R-02          40.0        8.5        bus
         1          202 2026-02-09    R-01          33.0       12.0        bus
         2          203 2026-02-10    R-01          35.0       12.0        bus
         3          204 2026-02-10    R-02          42.0        8.5        bus
         4          205 2026-02-11    R-03          18.0        0.0  bicicleta
         5          206 2026-02-11    R-99          22.0        NaN        NaN
         6          207 2026-02-12    R-02           NaN        8.5        bus
         7          208 2026-02-12    R-01          31.0       12.0        bus
         8          209 2026-02-13    R-01          36.0        NaN        bus
         9          210 2026-02-13    R-03          14.0        0.0  bicicleta

21. I don't understand this step about the multiindex... I imagine the purpose is simply to have a single column that is shared by both dataframes

In [31]:
df_all_trips = df_all_trips.reset_index(level=0).rename(columns={"level_0": "week"})
df_all_trips

,week,id_registro,fecha,id_ruta,duracion_min,costo_mxn,medio
0,week_one,101,2026-02-02,R-01,32.0,12.0,bus
1,week_one,102,2026-02-02,R-02,41.0,0.0,bicicleta
2,week_one,103,2026-02-03,R-01,46.0,NaN,NaN
3,week_one,104,2026-02-03,R-99,NaN,12.0,bus
4,week_one,105,2026-02-04,R-02,28.0,8.5,bus
5,week_one,106,2026-02-04,R-01,35.0,12.0,bus
6,week_one,107,2026-02-05,R-02,NaN,NaN,bicicleta
7,week_one,108,2026-02-05,R-03,15.0,0.0,bicicleta
8,week_one,109,2026-02-06,R-01,30.0,12.0,bus
9,week_one,110,2026-02-06,R-02,44.0,8.5,bus
0,week_two,201,2026-02-09,R-02,40.0,8.5,bus
1,week_two,202,2026-02-09,R-01,33.0,12.0,bus
2,week_two,203,2026-02-10,R-01,35.0,12.0,bus
3,week_two,204,2026-02-10,R-02,42.0,8.5,bus
4,week_two,205,2026-02-11,R-03,18.0,0.0,bicicleta
5,week_two,206,2026-02-11,R-99,22.0,NaN,NaN
6,week_two,207,2026-02-12,R-02,NaN,8.5,bus
7,week_two,208,2026-02-12,R-01,31.0,12.0,bus
8,week_two,209,2026-02-13,R-01,36.0,NaN,bus
9,week_two,210,2026-02-13,R-03,14.0,0.0,bicicleta

In [33]:
df_all_trips = df_all_trips.reset_index(drop=True)
df_all_trips

,week,id_registro,fecha,id_ruta,duracion_min,costo_mxn,medio
0,week_one,101,2026-02-02,R-01,32.0,12.0,bus
1,week_one,102,2026-02-02,R-02,41.0,0.0,bicicleta
2,week_one,103,2026-02-03,R-01,46.0,NaN,NaN
3,week_one,104,2026-02-03,R-99,NaN,12.0,bus
4,week_one,105,2026-02-04,R-02,28.0,8.5,bus
5,week_one,106,2026-02-04,R-01,35.0,12.0,bus
6,week_one,107,2026-02-05,R-02,NaN,NaN,bicicleta
7,week_one,108,2026-02-05,R-03,15.0,0.0,bicicleta
8,week_one,109,2026-02-06,R-01,30.0,12.0,bus
9,week_one,110,2026-02-06,R-02,44.0,8.5,bus
10,week_two,201,2026-02-09,R-02,40.0,8.5,bus
11,week_two,202,2026-02-09,R-01,33.0,12.0,bus
12,week_two,203,2026-02-10,R-01,35.0,12.0,bus
13,week_two,204,2026-02-10,R-02,42.0,8.5,bus
14,week_two,205,2026-02-11,R-03,18.0,0.0,bicicleta
15,week_two,206,2026-02-11,R-99,22.0,NaN,NaN
16,week_two,207,2026-02-12,R-02,NaN,8.5,bus
17,week_two,208,2026-02-12,R-01,31.0,12.0,bus
18,week_two,209,2026-02-13,R-01,36.0,NaN,bus
19,week_two,210,2026-02-13,R-03,14.0,0.0,bicicleta

22. It seems that what I did here was to remove the separation between the weeks and rather added it as crucial information to use.

In [34]:
df_all_trips.shape

(20, 7)

# Phase 5

24. As it is time to begin doing the merges, I will start with the most obvious one: combining the trips to the specific routes.

In [35]:
df_joined = pd.merge(
    df_all_trips,
    df_routes_clean,
    on="id_ruta",
    how="left",
    validate="many_to_one",
    indicator=True,
)
df_joined

,week,id_registro,fecha,id_ruta,duracion_min,costo_mxn,medio,nombre_ruta,id_zona,_merge
0,week_one,101,2026-02-02,R-01,32.0,12.0,bus,Ruta Centro-ENES,Z-01,both
1,week_one,102,2026-02-02,R-02,41.0,0.0,bicicleta,Ruta Campus Juriquilla,Z-02,both
2,week_one,103,2026-02-03,R-01,46.0,NaN,NaN,Ruta Centro-ENES,Z-01,both
3,week_one,104,2026-02-03,R-99,NaN,12.0,bus,NaN,NaN,left_only
4,week_one,105,2026-02-04,R-02,28.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
5,week_one,106,2026-02-04,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both
6,week_one,107,2026-02-05,R-02,NaN,NaN,bicicleta,Ruta Campus Juriquilla,Z-02,both
7,week_one,108,2026-02-05,R-03,15.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both
8,week_one,109,2026-02-06,R-01,30.0,12.0,bus,Ruta Centro-ENES,Z-01,both
9,week_one,110,2026-02-06,R-02,44.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
10,week_two,201,2026-02-09,R-02,40.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
11,week_two,202,2026-02-09,R-01,33.0,12.0,bus,Ruta Centro-ENES,Z-01,both
12,week_two,203,2026-02-10,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both
13,week_two,204,2026-02-10,R-02,42.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
14,week_two,205,2026-02-11,R-03,18.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both
15,week_two,206,2026-02-11,R-99,22.0,NaN,NaN,NaN,NaN,left_only
16,week_two,207,2026-02-12,R-02,NaN,8.5,bus,Ruta Campus Juriquilla,Z-02,both
17,week_two,208,2026-02-12,R-01,31.0,12.0,bus,Ruta Centro-ENES,Z-01,both
18,week_two,209,2026-02-13,R-01,36.0,NaN,bus,Ruta Centro-ENES,Z-01,both
19,week_two,210,2026-02-13,R-03,14.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both

In [36]:
print(df_joined["_merge"].value_counts())

_merge
both          18
left_only      2
right_only     0
Name: count, dtype: int64

24. What does the "_merge" do? I don't see it as a column, and the leading underscore makes me think that it is some kind of reserved syntax... I assume there might be parts of the dataframes in which information was only on one side. That is what `left_only` and `right_only` probably mean.

In [37]:
df_all_trips = df_all_trips.rename(columns={"_merge": "origin_cross_route"})
df_all_trips

,week,id_registro,fecha,id_ruta,duracion_min,costo_mxn,medio
0,week_one,101,2026-02-02,R-01,32.0,12.0,bus
1,week_one,102,2026-02-02,R-02,41.0,0.0,bicicleta
2,week_one,103,2026-02-03,R-01,46.0,NaN,NaN
3,week_one,104,2026-02-03,R-99,NaN,12.0,bus
4,week_one,105,2026-02-04,R-02,28.0,8.5,bus
5,week_one,106,2026-02-04,R-01,35.0,12.0,bus
6,week_one,107,2026-02-05,R-02,NaN,NaN,bicicleta
7,week_one,108,2026-02-05,R-03,15.0,0.0,bicicleta
8,week_one,109,2026-02-06,R-01,30.0,12.0,bus
9,week_one,110,2026-02-06,R-02,44.0,8.5,bus
10,week_two,201,2026-02-09,R-02,40.0,8.5,bus
11,week_two,202,2026-02-09,R-01,33.0,12.0,bus
12,week_two,203,2026-02-10,R-01,35.0,12.0,bus
13,week_two,204,2026-02-10,R-02,42.0,8.5,bus
14,week_two,205,2026-02-11,R-03,18.0,0.0,bicicleta
15,week_two,206,2026-02-11,R-99,22.0,NaN,NaN
16,week_two,207,2026-02-12,R-02,NaN,8.5,bus
17,week_two,208,2026-02-12,R-01,31.0,12.0,bus
18,week_two,209,2026-02-13,R-01,36.0,NaN,bus
19,week_two,210,2026-02-13,R-03,14.0,0.0,bicicleta

26. It is a bit strange that `_merge` was a column, as I don't remember defining it anywhere.... How does the `columns` attribute work? For now it seems that the "key" is the name of the column and the "value" (what comes after the `:`) is the thing that it is being renamed into.

In [38]:
df_all_trips_zones = pd.merge(
    df_all_trips,
    df_zones,
    on="id_zona",
    how="left",
    validate="many_to_one",
)

KeyError: 'id_zona'

28. I got an `KeyError: 'id_zona'` and I think this was caused by the duplicate! I did not provided the clean df for zones.

In [ ]:
df_all_trips_zones = pd.merge(
    df_all_trips,
    df_zones,
    on="id_zona",
    how="left",
    validate="many_to_one",
)

30. In fact, it seems that I have been working with the incorrect dataframe all along. I should probably put a number or something in order to have some notion of temporality.

In [39]:
df_joined_0 = df_joined.rename(columns={"_merge": "origin_cross_route"})
df_joined_0

,week,id_registro,fecha,id_ruta,duracion_min,costo_mxn,medio,nombre_ruta,id_zona,origin_cross_route
0,week_one,101,2026-02-02,R-01,32.0,12.0,bus,Ruta Centro-ENES,Z-01,both
1,week_one,102,2026-02-02,R-02,41.0,0.0,bicicleta,Ruta Campus Juriquilla,Z-02,both
2,week_one,103,2026-02-03,R-01,46.0,NaN,NaN,Ruta Centro-ENES,Z-01,both
3,week_one,104,2026-02-03,R-99,NaN,12.0,bus,NaN,NaN,left_only
4,week_one,105,2026-02-04,R-02,28.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
5,week_one,106,2026-02-04,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both
6,week_one,107,2026-02-05,R-02,NaN,NaN,bicicleta,Ruta Campus Juriquilla,Z-02,both
7,week_one,108,2026-02-05,R-03,15.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both
8,week_one,109,2026-02-06,R-01,30.0,12.0,bus,Ruta Centro-ENES,Z-01,both
9,week_one,110,2026-02-06,R-02,44.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
10,week_two,201,2026-02-09,R-02,40.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
11,week_two,202,2026-02-09,R-01,33.0,12.0,bus,Ruta Centro-ENES,Z-01,both
12,week_two,203,2026-02-10,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both
13,week_two,204,2026-02-10,R-02,42.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both
14,week_two,205,2026-02-11,R-03,18.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both
15,week_two,206,2026-02-11,R-99,22.0,NaN,NaN,NaN,NaN,left_only
16,week_two,207,2026-02-12,R-02,NaN,8.5,bus,Ruta Campus Juriquilla,Z-02,both
17,week_two,208,2026-02-12,R-01,31.0,12.0,bus,Ruta Centro-ENES,Z-01,both
18,week_two,209,2026-02-13,R-01,36.0,NaN,bus,Ruta Centro-ENES,Z-01,both
19,week_two,210,2026-02-13,R-03,14.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both

32. It seems that in the `origin_cross_route` column I work with things that overlap, and htat is the reason why I have some values that are present only on the left and some that are present only on the right.

In [44]:
df_zones_clean = df_zones.drop_duplicates(subset=["id_zona"], keep="first").copy()
df_zones_clean

df_joined_1 = pd.merge(
    df_joined_0,
    df_zones_clean,
    on="id_zona",
    how="left",
    validate="many_to_one",
)

df_joined_1

,week,id_registro,fecha,id_ruta,duracion_min,costo_mxn,medio,nombre_ruta,id_zona,origin_cross_route,nombre_zona
0,week_one,101,2026-02-02,R-01,32.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
1,week_one,102,2026-02-02,R-02,41.0,0.0,bicicleta,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
2,week_one,103,2026-02-03,R-01,46.0,NaN,NaN,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
3,week_one,104,2026-02-03,R-99,NaN,12.0,bus,NaN,NaN,left_only,NaN
4,week_one,105,2026-02-04,R-02,28.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
5,week_one,106,2026-02-04,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
6,week_one,107,2026-02-05,R-02,NaN,NaN,bicicleta,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
7,week_one,108,2026-02-05,R-03,15.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both,Zona Juriquilla-Norte
8,week_one,109,2026-02-06,R-01,30.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
9,week_one,110,2026-02-06,R-02,44.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
10,week_two,201,2026-02-09,R-02,40.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
11,week_two,202,2026-02-09,R-01,33.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
12,week_two,203,2026-02-10,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
13,week_two,204,2026-02-10,R-02,42.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
14,week_two,205,2026-02-11,R-03,18.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both,Zona Juriquilla-Norte
15,week_two,206,2026-02-11,R-99,22.0,NaN,NaN,NaN,NaN,left_only,NaN
16,week_two,207,2026-02-12,R-02,NaN,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
17,week_two,208,2026-02-12,R-01,31.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
18,week_two,209,2026-02-13,R-01,36.0,NaN,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
19,week_two,210,2026-02-13,R-03,14.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both,Zona Juriquilla-Norte

34. Why in this one I didn't use the `indicator=True` attribute? What does it do?

In [45]:
df_joined_1.shape

(20, 11)

36.
  1. ¿Existe algún registro clasificado como `left_only`? Yes, there are some
  2. De acuerdo con el diccionario de datos, ¿cuál es el código de ruta de ese registro y qué representa? It seems that in both cases, `left_only` is being used when I have missing values in my other columns, particularly in the ones that describe the code of the route.
  3. ¿Por qué es metodológicamente incorrecto eliminar esa fila del DataFrame o imputarle un valor calculado (como promedios) a sus características de forma automática? Because as it is a categorical column the reality is that there is no numeric way to get is value by doing any type of statistical difference. It wouldn't be correct to use any value unless we have some very clear information about the nature of that tuple (such as redundancy with other column that could guarantee us what value goes in there).

# Phase 6

In [46]:
print(f"Shape {df_joined_1.shape}")
print(f"Data Types {df_joined_1.dtypes}")
print(f"Missing Values {df_joined_1.isna().sum()}")

Shape (20, 11)
Data Types week                          object
id_registro                    int64
fecha                 datetime64[ns]
id_ruta                       object
duracion_min                 float64
costo_mxn                    float64
medio                         object
nombre_ruta                   object
id_zona                       object
origin_cross_route          category
nombre_zona                   object
dtype: object
Missing Values week                  0
id_registro           0
fecha                 0
id_ruta               0
duracion_min          3
costo_mxn             4
medio                 2
nombre_ruta           2
id_zona               2
origin_cross_route    0
nombre_zona           2
dtype: int64

## Technical report

37.
The data are is fabricated and its only use is academical. They were created for the ENES Juriquilla.  

The duplicated data are not an issue in certain scenarios, such as when there is a particular identificator of the routes. Deleating it would be a mistake, as while they might seem redundant those types of ids actually allow us to manipulate data cleanly by several sources. These are known in database theory as "one to many".

It could be argued that this data frame is not suitable for inference in any of its columns, as the tuples are very few (20 tuples), however assuming this is all the data we can have we are able to wokr on several columns:
- `duracion_min` allows us to explore its mean, average, etc. Its missing values should be ignored, as with the limited amount of data inputing could be wrong.
- `costo_mxn` allow us the same numeric exploration.  
- `medio`, `nombre_ruta` and `nombre_zona` all allow us to explore these in order of presence. We can very easily create histograms to see which one are the most and least common, etc.

In [47]:
df_joined_1

,week,id_registro,fecha,id_ruta,duracion_min,costo_mxn,medio,nombre_ruta,id_zona,origin_cross_route,nombre_zona
0,week_one,101,2026-02-02,R-01,32.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
1,week_one,102,2026-02-02,R-02,41.0,0.0,bicicleta,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
2,week_one,103,2026-02-03,R-01,46.0,NaN,NaN,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
3,week_one,104,2026-02-03,R-99,NaN,12.0,bus,NaN,NaN,left_only,NaN
4,week_one,105,2026-02-04,R-02,28.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
5,week_one,106,2026-02-04,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
6,week_one,107,2026-02-05,R-02,NaN,NaN,bicicleta,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
7,week_one,108,2026-02-05,R-03,15.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both,Zona Juriquilla-Norte
8,week_one,109,2026-02-06,R-01,30.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
9,week_one,110,2026-02-06,R-02,44.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
10,week_two,201,2026-02-09,R-02,40.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
11,week_two,202,2026-02-09,R-01,33.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
12,week_two,203,2026-02-10,R-01,35.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
13,week_two,204,2026-02-10,R-02,42.0,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
14,week_two,205,2026-02-11,R-03,18.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both,Zona Juriquilla-Norte
15,week_two,206,2026-02-11,R-99,22.0,NaN,NaN,NaN,NaN,left_only,NaN
16,week_two,207,2026-02-12,R-02,NaN,8.5,bus,Ruta Campus Juriquilla,Z-02,both,Zona Juriquilla-Norte
17,week_two,208,2026-02-12,R-01,31.0,12.0,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
18,week_two,209,2026-02-13,R-01,36.0,NaN,bus,Ruta Centro-ENES,Z-01,both,Zona Centro-Norte
19,week_two,210,2026-02-13,R-03,14.0,0.0,bicicleta,Ciclovía Jurica,Z-02,both,Zona Juriquilla-Norte